/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Simple SSE Notification API
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from './axios-instance';
export interface LoginRequest {
  username: string;
}

export interface LoginResponse {
  success?: boolean;
  username?: string;
}

export interface LogoutResponse {
  success?: boolean;
}

export interface NotifyRequest {
  from_username: string;
  /** A specific username or 'all' */
  target_username: string;
  message: string;
}

export interface NotifyResponse {
  success?: boolean;
}

export interface Notification {
  id?: string;
  from?: string;
  message?: string;
  timestamp?: string;
}

export interface UsersResponse {
  /** List of connected usernames */
  users?: string[];
}

export interface AcknowledgeRequestPayload {
  /** List of usernames to send acknowledgment request to */
  to_usernames: string[];
  /** Message for the acknowledgment request */
  message: string;
}

export interface AcknowledgeRequestResponse {
  success?: boolean;
  request_id?: string;
}

export interface AcknowledgeResponsePayload {
  /** ID of the acknowledgment request being responded to */
  request_id: string;
}

export interface AcknowledgeResponseResponse {
  success?: boolean;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getSimpleSSENotificationAPI = () => {
/**
 * @summary Logs a user in and creates a session
 */
const postLogin = (
    loginRequest: LoginRequest,
 options?: SecondParameter<typeof customInstance<LoginResponse>>,) => {
      return customInstance<LoginResponse>(
      {url: `/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest
    },
      options);
    }
  
/**
 * @summary Logs a user out and destroys the session
 */
const postLogout = (
    
 options?: SecondParameter<typeof customInstance<LogoutResponse>>,) => {
      return customInstance<LogoutResponse>(
      {url: `/logout`, method: 'POST'
    },
      options);
    }
  
/**
 * @summary Subscribes to the SSE notification stream (requires authentication)
 */
const getEvents = (
    
 options?: SecondParameter<typeof customInstance<string>>,) => {
      return customInstance<string>(
      {url: `/events`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Broadcasts a notification (requires authentication)
 */
const postNotify = (
    notifyRequest: NotifyRequest,
 options?: SecondParameter<typeof customInstance<NotifyResponse>>,) => {
      return customInstance<NotifyResponse>(
      {url: `/notify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: notifyRequest
    },
      options);
    }
  
/**
 * @summary Gets list of currently connected users (requires authentication)
 */
const getUsers = (
    
 options?: SecondParameter<typeof customInstance<UsersResponse>>,) => {
      return customInstance<UsersResponse>(
      {url: `/users`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Sends an acknowledgment request to user(s) (requires authentication)
 */
const postAcknowledgeRequest = (
    acknowledgeRequestPayload: AcknowledgeRequestPayload,
 options?: SecondParameter<typeof customInstance<AcknowledgeRequestResponse>>,) => {
      return customInstance<AcknowledgeRequestResponse>(
      {url: `/acknowledge/request`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: acknowledgeRequestPayload
    },
      options);
    }
  
/**
 * @summary Responds to an acknowledgment request (requires authentication)
 */
const postAcknowledgeResponse = (
    acknowledgeResponsePayload: AcknowledgeResponsePayload,
 options?: SecondParameter<typeof customInstance<AcknowledgeResponseResponse>>,) => {
      return customInstance<AcknowledgeResponseResponse>(
      {url: `/acknowledge/response`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: acknowledgeResponsePayload
    },
      options);
    }
  
return {postLogin,postLogout,getEvents,postNotify,getUsers,postAcknowledgeRequest,postAcknowledgeResponse}};
export type PostLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSimpleSSENotificationAPI>['postLogin']>>>
export type PostLogoutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSimpleSSENotificationAPI>['postLogout']>>>
export type GetEventsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSimpleSSENotificationAPI>['getEvents']>>>
export type PostNotifyResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSimpleSSENotificationAPI>['postNotify']>>>
export type GetUsersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSimpleSSENotificationAPI>['getUsers']>>>
export type PostAcknowledgeRequestResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSimpleSSENotificationAPI>['postAcknowledgeRequest']>>>
export type PostAcknowledgeResponseResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSimpleSSENotificationAPI>['postAcknowledgeResponse']>>>
